# Generated by Django 5.1.2 on 2024-10-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('empdep', models.CharField(max_length=50)),
                ('empmono', models.IntegerField()),
            ],
            options={
                'db_table': 'newemployee',
            },
        ),
    ]
