# Generated by Django 5.1.2 on 2024-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dep', models.CharField(max_length=50)),
                ('mono', models.IntegerField()),
            ],
            options={
                'db_table': 'doctordata',
            },
        ),
    ]
