# Generated by Django 5.1.2 on 2024-10-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employeedata',
        ),
    ]
