# Generated by Django 5.1.2 on 2024-10-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employeedata',
        ),
    ]
